# Generated by Django 5.0 on 2023-12-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarFormResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=255)),
                ('transmission', models.CharField(max_length=255)),
                ('owner_type', models.CharField(max_length=255)),
                ('mileage', models.FloatField()),
                ('engine', models.FloatField()),
                ('power', models.FloatField()),
                ('seats', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('kilometers_driven', models.IntegerField()),
                ('predicted_price', models.FloatField()),
            ],
        ),
    ]
