# Generated by Django 5.0.1 on 2024-01-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("mobile_number", models.CharField(max_length=10)),
                ("car_model", models.CharField(max_length=255)),
                ("car_year", models.IntegerField()),
                ("car_mileage", models.FloatField()),
                ("kilometers_driven", models.IntegerField()),
                ("person_image", models.ImageField(upload_to="person_images/")),
                ("car_image", models.ImageField(upload_to="car_images/")),
            ],
        ),
        migrations.AlterField(
            model_name="carformresult",
            name="seats",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="carformresult",
            name="transmission",
            field=models.CharField(max_length=250),
        ),
    ]
