# Generated by Django 5.0.1 on 2024-01-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_cardetails_alter_carformresult_seats_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("mobile_number", models.CharField(max_length=10)),
                ("car_model", models.CharField(max_length=255)),
                ("car_year", models.IntegerField()),
                ("mileage", models.IntegerField()),
                ("kilometers_driven", models.IntegerField()),
                ("person_image", models.ImageField(upload_to="person_images/")),
                ("car_image", models.ImageField(upload_to="car_images/")),
            ],
        ),
        migrations.DeleteModel(
            name="CarDetails",
        ),
    ]
