# Generated by Django 5.0.1 on 2024-01-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_uploadedformdata_delete_cardetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
